code: python setup

diff --git a/bin/setup/python b/bin/setup/python
--- a/bin/setup/python
+++ b/bin/setup/python
@@ -2,15 +2,22 @@
 
 ## PURPOSE: entrypoint for python setup
 
-##
-# optional
-# [[ "${BASH_SOURCE[0]}" != "${0}" ]] || { echo "ERROR: this file must be sourced from bash"; exit 1; }
+# exit if executed directly
+[[ "${BASH_SOURCE[0]}" != "${0}" ]] || { echo "ERROR: this file must be sourced from bash"; exit 1; }
+
+[[ "${BASH_SOURCE[0]}" != "${0}" ]] && echo "# ... loading ${BASH_SOURCE[0]}"
 
 [ "$EUID" = 0 ] || SUDO="sudo -EH" PIP_MODE="--user"
 
-## TODO: case PKG_TYPE in apk, apt, yum
-PKG_TYPE=yum
+[ -z PKG_TYPE ] || . ./bin/setup/bash
 
+PKG_TYPE=${PKG_TYPE:?required}
+
+set -a
+
+PYTHON_MAJOR_VERSION=$1
+
+PYTHON_MAJOR_VERSION=${PYTHON_MAJOR_VERSION:-3}
 
 
 ## REQUIREMENTS: 
@@ -20,42 +27,42 @@ PKG_TYPE=yum
 
 
 ## REF: https://docs.python.org/3/using/cmdline.html#environment-variables
-
-set -a
-
-## test current python environment
-
 ## REF: https://packaging.python.org/tutorials/installing-packages/#requirements-for-installing-packages
 ## REF: https://packaging.python.org/tutorials/installing-packages/#ensure-you-can-run-python-from-the-command-line
 ## 
-## TODO: pass in specific version
-#case $PYTHON_VERSION in
-#	2)
-	python2 --version &>/dev/null || $SUDO $PKG_TYPE install -y python
+
+case $PYTHON_MAJOR_VERSION in
+	2)
+	python2 --version &>/dev/null || ( [ "$PKG_TYPE" = "apt" ] && apt-get update; $SUDO $PKG_TYPE install -y python )
 	PY2_VERSION=$(python2 --version 2>&1 | awk '{print $2}')
-	## REF: https://docs.python.org/2/library/ensurepip.html
-	python2 -m ensurepip --upgrade --default-pip $PIP_MODE
+	pip --version || ( ( [ "$PKG_TYPE" = "apt" ] && apt-get install -y curl ) && curl -ls https://bootstrap.pypa.io/pip/2.7/get-pip.py | python )
 	python2 -m pip install --upgrade $PIP_MODE pip setuptools wheel virtualenv
 	pip2 --version
 	virtualenv -h &>/dev/null && PY2_VENV=available
-#	;;
+	;;
 
-#	3)
-	python3 --version &>/dev/null || $SUDO $PKG_TYPE install -y python3 python3-pip
+	3)
+	python3 --version &>/dev/null ||  ( [ "$PKG_TYPE" = "apt" ] && apt-get update; $SUDO $PKG_TYPE install -y python3 python3-pip )
 	PY3_VERSION=$(python3 --version 2>&1 | awk '{print $2}')
 	pip3 --version
 	python3 -m venv -h &>/dev/null && PY3_VENV=available
-#	;;
+	;;
 	
-#	4)
-	## just waiting for this mess
-#	;;
+	4)
+	echo "ERROR: not implemented
+	: REF: https://opensource.com/life/14/9/why-python-4-wont-be-python-3
+	: REF: https://www.reddit.com/r/Python/comments/7zvyhx/pep_563_mentions_python_40_whats_going_on/
+	: REF: https://twitter.com/gvanrossum/status/1306082472443084801
+	"
+	unset PYTHON_MAJOR_VERSION
+	;;
 	
-#	*)
-#	: PYTHON_VERSION=missing
-#	;;
+	*)
+	echo "ERROR: not implemented"
+	unset PYTHON_MAJOR_VERSION
+	;;
 
-#esac #PYTHON_MAJOR
+esac #PYTHON_MAJOR_VERSION
 
 set +a
 
